from pathlib import Path
from uuid import uuid4

import uvicorn
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, field_validator

from pdf_operations import PDFExtractor

app = FastAPI(title="PDF Processing Service")


class ProcessPDFRequest(BaseModel):
    """Body for POST /process-pdf. ``request_id`` is generated by the server."""

    pdf_path: str

    @field_validator("pdf_path")
    @classmethod
    def validate_pdf_path(cls, value: str) -> str:
        path = value.strip()
        if not path:
            raise ValueError("pdf_path must not be empty")
        if not path.lower().endswith(".pdf"):
            raise ValueError("pdf_path must point to a .pdf file")
        return path


@app.get("/health")
def health() -> dict:
    """Liveness check."""
    return {"status": "ok"}


@app.post("/process-pdf")
def process_pdf(request: ProcessPDFRequest) -> dict:
    """Extract metadata, text and tables from the PDF at ``pdf_path``.

    Raises:
        404: the file does not exist.
        400: the path is not a regular file.
        500: extraction failed.
    """
    request_id = str(uuid4())
    pdf_path = Path(request.pdf_path)

    if not pdf_path.exists():
        raise HTTPException(status_code=404, detail=f"PDF file not found: {pdf_path}")
    if not pdf_path.is_file():
        raise HTTPException(status_code=400, detail=f"pdf_path is not a file: {pdf_path}")

    try:
        with PDFExtractor(pdf_path) as extractor:
            data = extractor.extract_all()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except Exception as exc:  # noqa: BLE001 - surface any extraction failure to the client
        raise HTTPException(status_code=500, detail=f"PDF extraction failed: {exc}") from exc

    return {"request_id": request_id, "status": "success", "data": data}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
